"""add refresh token rotation fields

Revision ID: c4cbecd51b79
Revises: 6416d21853c6
Create Date: 2026-08-12 18:05:08.559643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4cbecd51b79'
down_revision: Union[str, Sequence[str], None] = '6416d21853c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_family', sa.String(length=36), nullable=False))
    op.add_column('refresh_tokens', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_token_family'), 'refresh_tokens', ['token_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_family'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'revoked_at')
    op.drop_column('refresh_tokens', 'token_family')
    # ### end Alembic commands ###
